### ISSUE TITLE
Inactive Domains

### ISSUE THREAD

**Issue by quidsup** [Ultimate-Hosts-Blacklist/quidsup_notrack_trackers#1]
I wanted to let you guys know that I've been experimenting with a bulk domain checker utilising the visiting stats and whois data from OpenDNS https://github.com/opendns/investigate-examples/blob/master/scripts.py in order to check if the domains in my NoTrack lists are still active.
This is pay for service I'm utilising and its quite heavily throttled. I've run it through about 25% of the list and removed a few of the domains no longer active.
https://gitlab.com/quidsup/notrack-blocklists/commit/00d0f09e882402812bba295e963b617d9cc49da1

Simply visiting the home page of each domain is a fairly poor way of checking if a tracking site exists as a lot of them try their best to disguise what they're actually doing.
Visitor stats from DNS should be a lot more accurate.

Now that I've a Python script written to check the whole list it will make ongoing maintenance a lot easier...

**Comment by funilrys** [comment]
Hi @quidsup,

Please take the time to read and review https://pyfunceble.readthedocs.io/en/latest/code/logic-representation.html#domain-testing

We don't "simply visiting the home page of each domain". We definitely do much more!

Cheers, Nissar

**Comment by quidsup** [comment]
Closing as was for info only
